### ISSUE TITLE
nprobe is compiled with FreeBSD 13

### ISSUE THREAD

**Issue by mimugmail** [ntop/opnsense#2]
Hi,

it seems the current version of nprobe was compiled on a 13 which wont work with current OPNsense/pfSense.
Sadly you need to compile it for both versions to make it compatible. 

If you need help about restructuring the repo I'm happy to help :)

```
root@scope1510-1:~ # /usr/local/etc/rc.d/nprobe start
Starting nprobe.
ld-elf.so.1: /usr/local/bin/nprobe: Undefined symbol "pthread_setname_np@FBSD_1.6"
/usr/local/etc/rc.d/nprobe: WARNING: failed to start nprobe
```

https://forums.freebsd.org/threads/glib-undefined-symbol-pthread_setname_np-fbsd_1-6.78959/

**Comment by lucaderi** [comment]
Unfortunately we are not yet making builds for FreeBSD 13 as you can see https://packages.ntop.org/FreeBSD/.

**Comment by mimugmail** [comment]
Maybe you got me wrong. I just updated a running setup from 21.7.2 to 21.7.5 with the new nprobe Version and get the error above (which claims you binary was compiled on 13)

**Comment by mimugmail** [comment]
I updated to the latest build and it seems fine now.

Version with error:
Installed packages to be UPGRADED:
        nprobe: 9.7.211125 -> 9.7.211205 [ntop]
        os-nprobe: 9.7.211125 -> 9.7.211205 [ntop]
        os-ntopng-enterprise: 5.1.211125 -> 5.1.211205 [ntop]

After upgrade it started up correctly.

As we discussed in out teams talk earlier this year, am I allowed to grab your repo binarys from time to time and load them into my repo so they are not updated every day?
