### ISSUE TITLE
opnsense needs txz on FreeBSD instead of pkg

### ISSUE THREAD

**Issue by mimugmail** [ntop/opnsense#3]
Hi,

since upgrade to OPNsensen 22.1 you get switched to new FreeBSD:13:amd64 abi, but it turns out you build the packages against pkg 1.17 which adds .pkg extension instead of .txz with 1.16. Maybe better to add this to your poudriere conf:

PKG_COMPRESSION_FORMAT=       txz

(and build with pkg 1.16)

The move to 1.17 will be done around with 22.1.2, so it will take around 1-2 months until fixed.

**Comment by lucaderi** [comment]
In fact the package files have a .pkg trailer
https://packages.ntop.org/FreeBSD/FreeBSD:13:amd64/latest/
