### ISSUE TITLE
Community option in UI generates incorrect config

### ISSUE THREAD

**Issue by Taralas** [ntop/opnsense#4]
Looks like line 40 of https://github.com/ntop/opnsense/blob/master/ntopng/plugins/net/ntopng-enterprise/src/opnsense/service/templates/OPNsense/Ntopng/ntopng.conf is missing an = at the end of the string

**Comment by cardigliano** [comment]
This is not a bug, = is not required

**Comment by Taralas** [comment]
Added per request from @lucaderi
